---
- name: GAD - Global Active Device Pair Management
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"
    hostgroup_name: "Prod-ESXi-28"
    primary_vol_id: 300
    quorum_id: 30
    desired_state: "present"
    path_group_id: 100

  tasks:
    - name: Create GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        state: "{{desired_state}}"
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        spec:
          copy_group_name: "copy_group_{{ primary_vol_id }}"
          copy_pair_name: "copy_pair_name_{{ primary_vol_id }}"
          primary_volume_id: "{{ primary_vol_id }}"
          secondary_pool_id: 0
          path_group_id: "{{path_group_id}}"
          secondary_hostgroups:
            - name: "{{ hostgroup_name }}"
              port: "CL1-D"
              enable_preferred_path: true
            - name: "{{ hostgroup_name }}"
              port: "CL2-D"
              enable_preferred_path: true
          primary_hostgroups:
            - name: "{{ hostgroup_name }}"
              port: "CL1-D"
              enable_preferred_path: true
            - name: "{{ hostgroup_name }}"
              port: "CL2-D"
              enable_preferred_path: true
          quorum_disk_id: "{{ quorum_id }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
